firstname = str(input())
lastname = str(input())
middlename = str(input())
age = str(input())
birthdate = str(input())
birthplace = str(input())
gender = str(input())
address = str(input())
emailaddress = str(input())
contactnumber = str(input())
civilstatus = str(input())
religion = str(input())
languages = str(input())
nationality = str(input())
father_sname = str(input())
mother_sname = str(input())

print("Hi, My name is", firstname, middlename, lastname)
print("I'm", age, "years old")
print("I was born on", birthdate)
print("I was born in", birthplace)
print("My gender is", gender)
print("My address is", address)
print("My email address is", emailaddress)
print("My contact number is", contactnumber)
print("My civil status is", civilstatus)
print("My religion is", religion)
print("My languages are", languages)
print("My nationality is", nationality)
print("My father's name is", father_sname)
print("My mother's name is", mother_sname)